project_name: lambda-lb-target-group-dns

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: lambda-lb-target-group-dns
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - linux
    flags:
      - -trimpath

archives:
  - id: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format: binary
  - id: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}.zip"
    format: zip
    files:
      - LICENSE
      - README.md
      - src: lambda-lb-target-group-dns
        dst: entrypoint

checksum:
  name_template: checksums.txt

changelog:
  use: github
