project_name: lambda-lb-target-group-dns

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: bootstrap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=lambda.norpc
