project_name: lambda-lb-target-group-dns

force_token: github

before:
  hooks:
    - go mod download

builds:
  - binary: bootstrap
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=lambda.norpc
    goarch:
      - amd64
      - arm64
    goos:
      - linux

archives:
  - id: binary
    name_template: "lambda-lb-target-group-dns-{{ .Os }}-{{ .Arch }}"
    format: binary
  - id: zip
    name_template: "lambda-lb-target-group-dns-{{ .Os }}-{{ .Arch }}"
    format: zip
    files:
      - LICENSE
      - README.md

dockers:
  - image_templates:
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.created={{ .Date }}
    dockerfile: Dockerfile-goreleaser
    extra_files:
      - LICENSE
      - README.md
  - image_templates:
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
    use: buildx
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.version=v{{ .Version }}
      - --label=org.opencontainers.image.revision={{ .Commit }}
      - --label=org.opencontainers.image.created={{ .Date }}
    goarch: arm64
    dockerfile: Dockerfile-goreleaser
    extra_files:
      - LICENSE
      - README.md

docker_manifests:
  - name_template: "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}"
    image_templates:
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}"
    image_templates:
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Major }}"
    image_templates:
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Major }}"
    image_templates:
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: docker.io/dex4er/lambda-lb-target-group-dns:latest
    image_templates:
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "docker.io/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"
  - name_template: public.ecr.aws/dex4er/lambda-lb-target-group-dns:latest
    image_templates:
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-amd64"
      - "public.ecr.aws/dex4er/lambda-lb-target-group-dns:v{{ .Version }}-linux-arm64"

checksum:
  name_template: checksums.txt

changelog:
  use: github
